use_frameworks!

target 'MZReduxKit_Example' do
  pod 'MZReduxKit', :path => '../'

  target 'MZReduxKit_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
